# Generated by Django 3.2.5 on 2021-07-04 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis_Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jenis', models.CharField(max_length=100)),
                ('jenis_buku', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ketegori_Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ketegori', models.CharField(max_length=100)),
                ('nama_kategori', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_buku', models.CharField(max_length=100)),
                ('nama_buku', models.CharField(max_length=100)),
                ('penerbit', models.CharField(max_length=100)),
                ('jumlah_buku', models.CharField(max_length=100)),
                ('jenis_buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buku.jenis_buku')),
                ('kategori_buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buku.ketegori_buku')),
            ],
        ),
    ]
